"""
synthetic_loader.py
Purpose: Data loader for synthetic halo/subhalo data from tng-synthetic-pipeline.
         Loads preprocessed .pt and .csv files directly without additional processing.
Inputs: config (dict) - Configuration dictionary from config.yaml
        synthetic_features.pt - PyTorch tensor file with node features
        synthetic_preprocessed_data.csv - CSV with halo metadata and groupings
Outputs: List[HaloData] - Normalized halo data objects
Config keys: data.synthetic.features_path, data.synthetic.csv_path, data.grouping, seed
"""

import os
import logging
from typing import List, Dict, Any, Optional, Tuple
import numpy as np
import pandas as pd
import torch

from data.loaders.base_loader import BaseDataLoader, HaloData, SubhaloData

logger = logging.getLogger(__name__)


class SyntheticLoader(BaseDataLoader):
    """
    Data loader for synthetic halo data generated by tng-synthetic-pipeline.

    The synthetic data is pre-processed and comes in two files:
    1. synthetic_features.pt: PyTorch tensor with subhalo features
    2. synthetic_preprocessed_data.csv: CSV with metadata and halo assignments

    This loader reads these files directly and converts them to the
    standard HaloData format.
    """

    def __init__(self, config: Dict[str, Any]):
        """
        Initialize the synthetic data loader.

        Args:
            config: Configuration dictionary from config.yaml
        """
        super().__init__(config)

        # Get paths from config
        synthetic_config = self.data_config.get('synthetic', {})
        self.features_path = synthetic_config.get(
            'features_path', 'data/raw/synthetic_features.pt'
        )
        self.csv_path = synthetic_config.get(
            'csv_path', 'data/raw/synthetic_preprocessed_data.csv'
        )

        # Grouping method
        self.grouping_method = self.data_config.get('grouping', 'fof')

        logger.info(f"SyntheticLoader initialized with features={self.features_path}, csv={self.csv_path}")

    def load_raw(self) -> Tuple[Optional[torch.Tensor], pd.DataFrame]:
        """
        Load raw synthetic data from .pt and .csv files.

        Returns:
            Tuple of (features_tensor, metadata_dataframe)
        """
        features = None
        df = None

        # Load PyTorch features if available
        if os.path.exists(self.features_path):
            features = torch.load(self.features_path, map_location='cpu')
            logger.info(f"Loaded features tensor with shape {features.shape}")
        else:
            logger.warning(f"Features file not found: {self.features_path}")

        # Load CSV metadata
        if os.path.exists(self.csv_path):
            df = pd.read_csv(self.csv_path)
            logger.info(f"Loaded CSV with {len(df)} rows and columns: {list(df.columns)}")
        else:
            # Generate synthetic data if files don't exist
            logger.warning(f"CSV file not found: {self.csv_path}. Generating synthetic data...")
            features, df = self._generate_synthetic_data()

        return features, df

    def _generate_synthetic_data(self) -> Tuple[torch.Tensor, pd.DataFrame]:
        """
        Generate synthetic halo data for testing/development.

        Creates realistic mock data following expected distributions
        for galaxy/halo properties.

        Returns:
            Tuple of (features_tensor, metadata_dataframe)
        """
        np.random.seed(self.seed)

        # Number of halos and subhalos per halo
        num_halos = 500
        min_subhalos = 3
        max_subhalos = 50

        records = []
        subhalo_id = 0

        for halo_idx in range(num_halos):
            # Halo properties (following realistic scaling relations)
            log_halo_mass = np.random.uniform(11.0, 15.0)  # log10(M_halo / M_sun)
            halo_mass = 10 ** log_halo_mass

            # Number of subhalos scales with halo mass
            expected_subhalos = int(5 * (halo_mass / 1e12) ** 0.5)
            num_subhalos = np.clip(expected_subhalos + np.random.randint(-2, 3),
                                   min_subhalos, max_subhalos)

            # Halo center position
            halo_center = np.random.uniform(-50, 50, size=3)  # Mpc
            halo_velocity = np.random.normal(0, 200, size=3)  # km/s

            for i in range(num_subhalos):
                # Subhalo position relative to halo center
                r = np.random.exponential(0.5)  # Mpc, NFW-like profile
                theta = np.random.uniform(0, np.pi)
                phi = np.random.uniform(0, 2 * np.pi)
                offset = r * np.array([
                    np.sin(theta) * np.cos(phi),
                    np.sin(theta) * np.sin(phi),
                    np.cos(theta)
                ])
                position = halo_center + offset

                # Velocity with dispersion
                vel_disp = 100 * (halo_mass / 1e12) ** 0.25  # km/s
                velocity = halo_velocity + np.random.normal(0, vel_disp, size=3)

                # Stellar mass (Moster et al. stellar-to-halo mass relation)
                log_stellar = log_halo_mass - 1.5 - np.abs(np.random.normal(0, 0.3))
                stellar_mass = max(10 ** log_stellar, 1e6)

                # Half-mass radius (size-mass relation)
                half_mass_r = 0.001 * (stellar_mass / 1e10) ** 0.25  # Mpc

                # Metallicity (mass-metallicity relation)
                metallicity = 0.02 * (stellar_mass / 1e10) ** 0.3

                records.append({
                    'subhalo_id': subhalo_id,
                    'halo_id': halo_idx,
                    'cluster_id': f'halo_{halo_idx:05d}',
                    'x': position[0],
                    'y': position[1],
                    'z': position[2],
                    'vx': velocity[0],
                    'vy': velocity[1],
                    'vz': velocity[2],
                    'stellar_mass': stellar_mass,
                    'velocity_dispersion': vel_disp,
                    'half_mass_radius': half_mass_r,
                    'metallicity': metallicity,
                    'halo_mass': halo_mass,
                    'log_halo_mass': log_halo_mass,
                    'redshift': 0.0
                })
                subhalo_id += 1

        df = pd.DataFrame(records)

        # Create features tensor (N x 4)
        features = torch.tensor(
            df[['stellar_mass', 'velocity_dispersion', 'half_mass_radius', 'metallicity']].values,
            dtype=torch.float32
        )

        # Save generated data
        os.makedirs(os.path.dirname(self.csv_path) or 'data/raw', exist_ok=True)
        df.to_csv(self.csv_path, index=False)
        torch.save(features, self.features_path)
        logger.info(f"Generated and saved synthetic data: {len(df)} subhalos in {num_halos} halos")

        return features, df

    def _parse_subhalo(self, raw_record: pd.Series) -> SubhaloData:
        """
        Parse a single row from the CSV into a SubhaloData object.

        Args:
            raw_record: pandas Series representing one subhalo

        Returns:
            SubhaloData object with normalized fields
        """
        # Handle different possible column names
        position = np.array([
            raw_record.get('x', raw_record.get('pos_x', 0.0)),
            raw_record.get('y', raw_record.get('pos_y', 0.0)),
            raw_record.get('z', raw_record.get('pos_z', 0.0))
        ], dtype=np.float32)

        velocity = np.array([
            raw_record.get('vx', raw_record.get('vel_x', 0.0)),
            raw_record.get('vy', raw_record.get('vel_y', 0.0)),
            raw_record.get('vz', raw_record.get('vel_z', 0.0))
        ], dtype=np.float32)

        return SubhaloData(
            subhalo_id=int(raw_record.get('subhalo_id', raw_record.name)),
            position=position,
            velocity=velocity,
            stellar_mass=float(raw_record.get('stellar_mass', 1e10)),
            velocity_dispersion=float(raw_record.get('velocity_dispersion',
                                                      raw_record.get('vel_disp', 100.0))),
            half_mass_radius=float(raw_record.get('half_mass_radius',
                                                   raw_record.get('half_mass_r', 0.001))),
            metallicity=float(raw_record.get('metallicity', 0.02))
        )

    def _parse_all_subhalos(self, raw_data: Tuple[Optional[torch.Tensor], pd.DataFrame]) -> List[SubhaloData]:
        """
        Parse all subhalos from the DataFrame.

        Args:
            raw_data: Tuple of (features_tensor, metadata_df)

        Returns:
            List of SubhaloData objects
        """
        _, df = raw_data

        subhalos = []
        for idx, row in df.iterrows():
            try:
                subhalo = self._parse_subhalo(row)
                subhalos.append(subhalo)
            except Exception as e:
                logger.warning(f"Failed to parse subhalo at row {idx}: {e}")

        return subhalos

    def _group_into_halos(
        self,
        subhalos: List[SubhaloData],
        raw_data: Tuple[Optional[torch.Tensor], pd.DataFrame]
    ) -> List[HaloData]:
        """
        Group subhalos into their parent halos using halo_id from CSV.

        Args:
            subhalos: List of parsed SubhaloData objects
            raw_data: Tuple of (features_tensor, metadata_df)

        Returns:
            List of HaloData objects
        """
        _, df = raw_data

        # Build mapping from halo_id to subhalos
        halo_subhalos: Dict[Any, List[SubhaloData]] = {}
        halo_metadata: Dict[Any, Dict[str, Any]] = {}

        for idx, subhalo in enumerate(subhalos):
            row = df.iloc[idx]

            # Get halo identifier
            halo_id = row.get('halo_id', row.get('cluster_id', row.get('SubhaloGrNr', idx)))
            cluster_id = str(row.get('cluster_id', f'halo_{halo_id}'))

            if halo_id not in halo_subhalos:
                halo_subhalos[halo_id] = []
                halo_metadata[halo_id] = {
                    'cluster_id': cluster_id,
                    'halo_mass': float(row.get('halo_mass', row.get('Group_M_Crit200', 1e12))),
                    'redshift': float(row.get('redshift', 0.0))
                }

            halo_subhalos[halo_id].append(subhalo)

        # Create HaloData objects
        halos = []
        for halo_id, subhalo_list in halo_subhalos.items():
            if len(subhalo_list) == 0:
                continue

            meta = halo_metadata[halo_id]
            halo = HaloData(
                cluster_id=meta['cluster_id'],
                subhalos=subhalo_list,
                halo_mass=meta['halo_mass'],
                redshift=meta['redshift'],
                metadata={'halo_id': halo_id, 'source': 'synthetic'}
            )
            halos.append(halo)

        # Sort by cluster_id for reproducibility
        halos.sort(key=lambda h: h.cluster_id)

        return halos

    def load_with_features(self) -> Tuple[List[HaloData], Optional[torch.Tensor]]:
        """
        Load halos and return raw features tensor for direct use.

        Returns:
            Tuple of (halos, features_tensor)
        """
        raw_data = self.load_raw()
        features, df = raw_data

        subhalos = self._parse_all_subhalos(raw_data)
        halos = self._group_into_halos(subhalos, raw_data)

        self._halos = halos
        self._validate_data()

        return halos, features

    def get_feature_tensor(self) -> torch.Tensor:
        """
        Get the raw features tensor for all subhalos.

        Returns:
            Tensor of shape (N, 4) with [stellar_mass, vel_disp, half_mass_r, metallicity]
        """
        if self._halos is None:
            self.load()

        # Collect all features
        features = []
        for halo in self._halos:
            for subhalo in halo.subhalos:
                features.append([
                    subhalo.stellar_mass,
                    subhalo.velocity_dispersion,
                    subhalo.half_mass_radius,
                    subhalo.metallicity
                ])

        return torch.tensor(features, dtype=torch.float32)


def create_synthetic_dataset(
    num_halos: int = 500,
    output_dir: str = 'data/raw',
    seed: int = 42
) -> Tuple[str, str]:
    """
    Standalone function to generate synthetic dataset files.

    Args:
        num_halos: Number of halos to generate
        output_dir: Directory to save files
        seed: Random seed for reproducibility

    Returns:
        Tuple of (features_path, csv_path)
    """
    config = {
        'seed': seed,
        'data': {
            'synthetic': {
                'features_path': os.path.join(output_dir, 'synthetic_features.pt'),
                'csv_path': os.path.join(output_dir, 'synthetic_preprocessed_data.csv')
            },
            'grouping': 'fof'
        }
    }

    loader = SyntheticLoader(config)
    loader.load()

    return config['data']['synthetic']['features_path'], config['data']['synthetic']['csv_path']
